name: snapit-l4
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.1
  - pip
  - pip:
      - numpy==1.26.4
      - matplotlib==3.8.4
      - networkx==3.3
      - Markdown==3.7
      - scikit-learn==1.5.2
      - tensorboard==2.17.1
      - requests==2.32.3
